name: BAPhotoCreatorEnv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - tensorflow
  - pillow
  - matplotlib
  - pip
  - pip:
    - flask==3.0.0 
